services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-server
    ports:
      - "8000:8000"
    image: fastapi_app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - SECRET_KEY=devsecretchangeme
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ALGORITHM=HS256
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
